mariadb:
  image: kollaglue/fedora-rdo-mariadb
  environment:
   - DB_ROOT_PASSWORD=admin
keystone:
  image: kollaglue/fedora-rdo-keystone
  links:
   # Use maria to store all identity info
   - mariadb
  environment:
   - DB_ROOT_PASSWORD=admin
   # Needed for keystone initialization
   - KEYSTONE_ADMIN_TOKEN=secret
   - KEYSTONE_ADMIN_PASSWORD=kolla
   - KEYSTONE_DB_PASSWORD=keystonepwd
glancereg:
  image: kollaglue/fedora-rdo-glance-registry
  links:
   - mariadb
  environment:
   - DB_ROOT_PASSWORD=admin
   - GLANCE_DB_PASSWORD=glancedbpwd
   # TODO why is this needed if the keystone image isn't even linked
   - GLANCE_KEYSTONE_PASSWORD=glancekeypwd
glanceapi:
  image: kollaglue/fedora-rdo-glance-api
  links:
   - keystone
   # Until https://github.com/docker/compose/issues/869 is implemented fig 
   # can't produce container names like glance_registry, so we are stuck with
   # glancereg and so have to use an alias in the links here so that
   # ultimately the *_PORT_*_TCP_ADDR env vars, e.g. 
   # GLANCE_REGISTRY_PORT_9191_TCP_ADDR, come out in a way that is usable by
   # fedora-rdo-base/service_hosts.sh
   - glancereg:glance_registry 
   # Only needed for sending notifications, which ceil. then picks up
   - rabbitmq
  environment:
   # Needed to allow creation of keystone user for glance
   # TODO I think we only need one of these
   - KEYSTONE_ADMIN_TOKEN=secret
   - KEYSTONE_ADMIN_PASSWORD=kolla
   # TODO not sure the DB password is actually needed since
   # we're only using v1 of the glance api right now.
   # Could try setting this to a bogus value
   - GLANCE_DB_PASSWORD=glancedbpwd
   # Needed for glance keystone user
   - GLANCE_KEYSTONE_PASSWORD=glancekeypwd
rabbitmq:
  image: kollaglue/fedora-rdo-rabbitmq
  environment:
   - RABBITMQ_PASS=guest
  ports:
   # we've enabled the rabbitmq-management plugin by turning on tracing, 
   # so might as well expose the HTTP interface on the container and host
   - "15672:15672"
ceilapi:
  image: kollaglue/fedora-rdo-ceilometer-api 
  links:
   # TODO not quite sure why this needs rabbit access 
   - rabbitmq
   # We're storing all ceilometer day in mariadb
   - mariadb
   # Needed to authenticate api users
   - keystone
  environment:
   # TODO not quite sure why this needs rabbit access
   - RABBITMQ_PASS=guest
   # TODO override CEILOMETER_KEYSTONE_USER and
   # CEILOMETER_ADMIN_PASSWORD so we don't reuse the admin keystone user 
   #
   # Needed to allow creation of keystone user for ceil
   # TODO I think we only need one of these
   - KEYSTONE_ADMIN_TOKEN=secret
   - KEYSTONE_ADMIN_PASSWORD=kolla
   # Needed to create ceil DB
   - DB_ROOT_PASSWORD=admin
   # Needed for creation and access to ceil DB
   - CEILOMETER_DB_USER=ceilometer
   - CEILOMETER_DB_PASSWORD=ceildbpwd
   - CEILOMETER_DB_NAME=ceilometer
ceilcoll:
  image: kollaglue/fedora-rdo-ceilometer-collector
  links:
   # We're storing all ceilometer day in mariadb
   - mariadb
   # Needed to get samples from ceilnotif and ceilcentral
   - rabbitmq
  environment:
   - CEILOMETER_DB_USER=ceilometer
   - CEILOMETER_DB_PASSWORD=ceildbpwd
   - CEILOMETER_DB_NAME=ceilometer
   - RABBITMQ_PASS=guest
   # TODO why are these needed?
   - KEYSTONE_ADMIN_TOKEN=secret
   - DB_ROOT_PASSWORD=admin
ceilcentral:
  image: kollaglue/fedora-rdo-ceilometer-central
  links:
   # Needed for sending samples, which ceilcoll then receives
   - rabbitmq
   # Needed to lookup the location of the services being polled
   - keystone
   # Needed to poll the actual services being monitored, just glance now
   - glanceapi
  environment:
   - RABBITMQ_PASS=guest
   # TODO remove check for this 
   - CEILOMETER_DB_PASSWORD=ceildbpwd-bad
   # TODO whis is this needed?
   - KEYSTONE_ADMIN_TOKEN=secret
   # TODO remove check for this
   - DB_ROOT_PASSWORD=admin-bad
ceilnotif:
  image: kollaglue/fedora-rdo-ceilometer-notification 
  links:
   - rabbitmq
  environment:
   - RABBITMQ_PASS=guest
   # TODO remove checks for these
   - CEILOMETER_DB_PASSWORD=ceildbpwd-bad
   - KEYSTONE_ADMIN_TOKEN=secret-bad
   - DB_ROOT_PASSWORD=admin-bad
