mariadb:
  image: kollaglue/fedora-rdo-mariadb
  environment:
   - DB_ROOT_PASSWORD=admin
#  # help with debugging from host
#  ports:
#   - "8000:3306"
#  # setup gating
#  volumes:
#   - /tmp/gate:/tmp/gate
#  command: mysqld
keystone:
  image: kollaglue/fedora-rdo-keystone
  links:
   - mariadb
  environment:
   - DB_ROOT_PASSWORD=admin
   - KEYSTONE_ADMIN_TOKEN=secret
   - KEYSTONE_ADMIN_PASSWORD=kolla
   - KEYSTONE_DB_PASSWORD=keystonepwd
glancereg:
  image: kollaglue/fedora-rdo-glance-registry
  links:
   - mariadb
  environment:
   - DB_ROOT_PASSWORD=admin
   - GLANCE_DB_PASSWORD=glancedbpwd
   - GLANCE_KEYSTONE_PASSWORD=glancekeypwd
glanceapi:
  image: kollaglue/fedora-rdo-glance-api
  links:
   - keystone
   # until https://github.com/docker/fig/issues/799 is implemented fig can't
   # produce container names like glance_registry, so we are stuck with
   # glancereg and so have to use an alias in the links here so that
   # ultimately the *_PORT_*_TCP_ADDR env vars, e.g. 
   # GLANCE_REGISTRY_PORT_9191_TCP_ADDR, come out right.
   - glancereg:glance_registry 
   # for sending notifs to ceil.
   - rabbitmq
  environment:
   # TODO are these set already due to linking to keystone container?
   - KEYSTONE_ADMIN_TOKEN=secret
   - KEYSTONE_ADMIN_PASSWORD=kolla
   # not sure the DB password is actually needed since
   # we're only using v1 of the glance api right now.
   # Could try setting this to a bogus value
   - GLANCE_DB_PASSWORD=glancedbpwd
   - GLANCE_KEYSTONE_PASSWORD=glancekeypwd
rabbitmq:
  image: kollaglue/fedora-rdo-rabbitmq
  environment:
   - RABBITMQ_PASS=guest
ceilapi:
  image: kollaglue/fedora-rdo-ceilometer-api 
  links: 
   - rabbitmq
   - mariadb
   - keystone
  environment:
   - RABBITMQ_PASS=guest
   - DB_ROOT_PASSWORD=admin
   - KEYSTONE_ADMIN_TOKEN=secret
   - CEILOMETER_DB_USER=ceilometer
   - CEILOMETER_DB_PASSWORD=ceildbpwd
   - CEILOMETER_DB_NAME=ceilometer
ceilcoll:
  image: kollaglue/fedora-rdo-ceilometer-collector
  links:
   - mariadb
   - rabbitmq
  environment:
   - CEILOMETER_DB_USER=ceilometer
   - CEILOMETER_DB_PASSWORD=ceildbpwd
   - CEILOMETER_DB_NAME=ceilometer
   - RABBITMQ_PASS=guest
   # why are these needed?
   - KEYSTONE_ADMIN_TOKEN=secret
   - DB_ROOT_PASSWORD=admin
ceilnotif:
  image: kollaglue/fedora-rdo-ceilometer-notification 
  links:
   - rabbitmq
   - mariadb
  environment:
   - RABBITMQ_PASS=guest
   - CEILOMETER_DB_PASSWORD=ceildbpwd
   # why are these needed?
   - KEYSTONE_ADMIN_TOKEN=secret
   - DB_ROOT_PASSWORD=admin
